theme: jekyll-theme-cayman
description: "A repository for sharing datasets from the Shuishan(Sequoia) eLearning platform"
#google_analytics: G-E6L182MBVJ
use_umami: true
assets: true

languages:
  - en
  - cn

github:
  # Edit the following lines to customize the repository
  is_project_page: true
  repository_url: https://github.com/dbbDylan/shuishan-datasets
  repository_name: SHUISHAN-DATASETS
  owner_name: dbbDylan
  owner_url: https://github.com/dbbDylan

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

plugins:
  - jekyll-multiple-languages-plugin
