name: Sync README and Deploy to Pages

on:
  # Only trigger on changes to the README.md file in the master branch
  push:
    branches:
      - master
    paths:
      - 'README.md'  # Only trigger if README.md is changed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      deploy-branch:
        description: 'Branch to deploy to'
        required: true
        default: 'gh-pages'  # Default target branch (can be changed during manual trigger)

jobs:
  update-readme-on-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Checkout deploy branch or create if not exists
      run: |
        git checkout ${{ github.event.inputs.deploy-branch }} || git checkout --orphan ${{ github.event.inputs.deploy-branch }} # If the branch doesn't exist, create it
        git pull origin ${{ github.event.inputs.deploy-branch }}

    - name: Sync README.md to deploy branch
      run: |
        git checkout master -- README.md
        cp README.md index.md # Copy README.md to index.md
        ls -l

    - name: Add, commit, and push to deploy branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md index.md
        git commit -m "Sync README.md and update index.md on ${{ github.event.inputs.deploy-branch }} branch" --no-verify
        git push origin ${{ github.event.inputs.deploy-branch }} --no-verify
